import { test, expect } from '@playwright/test';

test.describe('Export HTML documentation', () => {
  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => { try { localStorage.clear(); } catch { /* ignore */ } });
    await page.goto('/');
    await page.waitForSelector('[data-testid="canvas-container"]');
  });

  test('HTML format button is visible in the export dialog', async ({ page }) => {
    await page.getByTestId('add-table-btn').click();
    await page.getByTestId('export-btn').click();
    await expect(page.getByTestId('export-dialog')).toBeVisible();
    await expect(page.getByTestId('export-format-html')).toBeVisible();
  });

  test('HTML preview shows the generated document source', async ({ page }) => {
    await page.getByTestId('add-table-btn').click();

    // Rename the table so we can assert a distinctive token ends up in the preview.
    const tableNameSpan = page.locator('[data-testid^="table-name-"]').first();
    await tableNameSpan.dblclick();
    const input = page.locator('[data-testid^="table-name-input-"]').first();
    await input.fill('customers');
    await input.press('Enter');

    await page.getByTestId('export-btn').click();
    await page.getByTestId('export-format-html').click();

    const preview = page.getByTestId('export-preview');
    await expect(preview).toContainText('<!DOCTYPE html>');
    await expect(preview).toContainText('customers');
    await expect(preview).toContainText('Generated by Tabloid');
  });

  test('HTML Copy button is available for copy-to-clipboard flow', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    await page.getByTestId('add-table-btn').click();
    await page.getByTestId('export-btn').click();
    await page.getByTestId('export-format-html').click();
    await expect(page.getByTestId('export-copy-btn')).toBeVisible();

    await page.getByTestId('export-copy-btn').click();
    const clip = await page.evaluate(() => navigator.clipboard.readText());
    expect(clip).toContain('<!DOCTYPE html>');
  });
});
